### PR TITLE
Issue #59 - Path on Mac OSX

### PR DESCRIPTION
**Pull request by mjarosch**
This is a fix for issue #59. Switch from hard coded directory separators to system constants. I am having troubles getting the tests to run on my Mac right now, so I am unable to verify that I didn't break anything.

### CODE REVIEW

**Comment by blipson89** [comment]
Thank you @mjarosch! This looks good, but I'm actually on vacation until next week and I can't easily validate it until I'm back.

I'll test it on Windows and Linux when I get home. If it all checks out, I'll look to cut a release after Christmas.

Thanks!

**Comment by mjarosch** [comment]
@blipson89 Enjoy your vacation and check it out when you get back. Maybe you can help me figure out where I am going wrong with the tests at that time as well.

**Comment by mjarosch** [comment]
Hi @blipson89, hope your vacation was good. Would you be able to help me figure out why I am unable to run the tests?

**Comment by blipson89** [comment]
When I upgraded to .NET 6.0 recently, the test runner broke. I fixed it on my local but it looks like I didn't commit it. I'll push that up now.

**Comment by mjarosch** [comment]
Pulled in your changes and it's not finding any tests to run. I am using "dotnet test --framework net6.0" to try and run the tests.

```
 Leprechaun.Tests -> /Users/mjarosch/Developer/Web/Leprechaun/src/Leprechaun.Tests/bin/Debug/net6.0/Leprechaun.Tests.dll
Test run for /Users/mjarosch/Developer/Web/Leprechaun/src/Leprechaun.Tests/bin/Debug/net6.0/Leprechaun.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in /Users/mjarosch/Developer/Web/Leprechaun/src/Leprechaun.Tests/bin/Debug/net6.0/Leprechaun.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Comment by mjarosch** [comment]
I added the xunit.runner.visualstudio package and it is now finding tests. 76 tests found and passed in Visual Studio on Windows. 28 found and passed on OSX (after I fixed one test to use the path separator constant instead of a hard coded slash).

It looks like the Rainbow tests are not working on OSX and the Console tests are not working on Windows or OSX.

**Comment by blipson89** [comment]
Hi @mjarosch, I dug into it a bit:

I was using Rider instead of VisualStudio and it was able to run the tests fine, but when I tried on VS it didn't work. `xunit.runner.visualstudio` did fix it. 

`Leprechaun.Console` has a test project, but no tests right now.

Rainbow relies on Sitecore dlls which are only .NET Framework, which is why `Leprechaun.InputProviders.Rainbow` still targets net472. I suppose that means Leprechaun set to Rainbow mode would not be able to run on OSX. 

The dotnet tool Leprechaun.Cli running in Rainbow mode isn't a _true_ .NET Core app. Under the hood, it's executing the legacy .NET Framework `.exe` in a child process in order to use .NET Framework dlls. Note: this only affects the `/r` command line switch. If you're using Leprechaun with Sitecore serialization, it is 100% dotnet core. 

I'm going to merge this into develop though as it all seems to be working both in unit tests and live tests.

**Pull request merged**
